import type { TemplateRegistryEntry } from '../contracts/index.js';

export const EXPANSION_TEMPLATE_REGISTRY: TemplateRegistryEntry[] = [
  {
    metadata: {
      id: 'exp-dog-corgi',
      name: 'Corgi Dog',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'dog',
      tags: ['dog', 'corgi', 'pet', 'cute', 'puppy', 'canine', 'companion'],
      styleTags: ['cute', 'compact', 'stylized', 'playful'],
      shapeTags: ['four_legged', 'short_legged', 'tailed', 'front_facing', 'long_body'],
      colorTags: ['brown', 'white', 'black', 'cream', 'tan'],
      complexity: 'medium',
      voxelBudgetRange: { min: 140, max: 210 },
      symmetry: 'soft',
      editableParts: ['ears', 'tail', 'legs', 'palette', 'face'],
      promptAliases: ['dog', 'corgi', 'puppy', 'cute dog', 'small dog', 'pet dog', 'corgi dog', 'little puppy'],
      negativeKeywords: ['car', 'bus', 'castle', 'robot', 'airplane', 'house', 'building', 'boat', 'truck'],
      rebuildSuitability: 'high',
      priority: 94,
      status: 'active',
      description:
        'A compact voxel corgi template suited for pet and cute animal prompts. ' +
        'Supports ear, tail, leg, and snout adjustments with selectable face styles.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/dogCorgiGenerator.ts#generateDogCorgi',
    },
  },
  {
    metadata: {
      id: 'exp-fox-sitting',
      name: 'Sitting Fox',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'fox',
      tags: ['fox', 'animal', 'forest', 'wildlife', 'cute', 'red fox', 'arctic fox', 'canid'],
      styleTags: ['stylized', 'cute', 'storybook', 'compact'],
      shapeTags: ['tailed', 'pointed_ears', 'slim_face', 'seated'],
      colorTags: ['orange', 'white', 'black', 'cream', 'brown'],
      complexity: 'medium',
      voxelBudgetRange: { min: 145, max: 215 },
      symmetry: 'soft',
      editableParts: ['ears', 'tail', 'snout', 'palette', 'pose'],
      promptAliases: ['fox', 'red fox', 'cute fox', 'forest fox', 'sitting fox', 'arctic fox', 'small fox', 'fox pet'],
      negativeKeywords: ['truck', 'bus', 'castle', 'robot', 'dragon', 'car', 'house', 'boat', 'train'],
      rebuildSuitability: 'high',
      priority: 93,
      status: 'active',
      description:
        'A seated fox template with strong tail and ear identity for wildlife and cute-animal prompts. ' +
        'Supports palette, tail, ear, and snout customization for adapt workflows.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/foxSittingGenerator.ts#generateFoxSitting',
    },
  },
  {
    metadata: {
      id: 'exp-penguin-standing',
      name: 'Standing Penguin',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'penguin',
      tags: ['penguin', 'bird', 'winter', 'animal', 'cute', 'baby penguin', 'antarctic', 'seabird'],
      styleTags: ['cute', 'soft', 'mascot', 'compact'],
      shapeTags: ['upright', 'round', 'short_winged', 'black_white'],
      colorTags: ['black', 'white', 'yellow', 'orange', 'gray'],
      complexity: 'medium',
      voxelBudgetRange: { min: 135, max: 205 },
      symmetry: 'soft',
      editableParts: ['beak', 'wings', 'belly', 'palette', 'head'],
      promptAliases: [
        'penguin',
        'cute penguin',
        'baby penguin',
        'winter penguin',
        'standing penguin',
        'small penguin',
        'penguin mascot',
        'antarctic penguin',
      ],
      negativeKeywords: ['car', 'truck', 'castle', 'robot', 'house', 'bus', 'boat', 'airplane', 'dragon'],
      rebuildSuitability: 'high',
      priority: 91,
      status: 'active',
      description:
        'An upright penguin template with editable wings, beak, belly, and head shape. ' +
        'Designed for winter, mascot, and baby-penguin prompts in reuse or adapt routes.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/penguinStandingGenerator.ts#generatePenguinStanding',
    },
  },
  {
    metadata: {
      id: 'exp-turtle-low',
      name: 'Low Turtle',
      sourceType: 'generator',
      baseCategory: 'animal',
      subCategory: 'turtle',
      tags: ['turtle', 'sea turtle', 'animal', 'shell', 'cute', 'pond turtle', 'reptile', 'shelled animal'],
      styleTags: ['cute', 'compact', 'soft', 'low_poly', 'storybook'],
      shapeTags: ['low_profile', 'shelled', 'four_legged', 'rounded', 'short_headed', 'wide_body'],
      colorTags: ['green', 'brown', 'yellow', 'olive', 'cream'],
      complexity: 'medium',
      voxelBudgetRange: { min: 130, max: 195 },
      symmetry: 'soft',
      editableParts: ['shell', 'head', 'legs', 'palette', 'pose', 'shellPattern'],
      promptAliases: ['turtle', 'sea turtle', 'cute turtle', 'small turtle', 'pond turtle', 'green turtle', 'little turtle'],
      negativeKeywords: ['car', 'bus', 'castle', 'robot', 'airplane', 'truck', 'house', 'building', 'penguin', 'bird'],
      rebuildSuitability: 'high',
      priority: 90,
      status: 'active',
      description:
        'A low-profile turtle template with a rounded shell, short head, four flippers, and editable shell pattern. ' +
        'Designed for pond, sea-turtle, and cute reptile prompts where a stable wide silhouette matters.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/turtleLowGenerator.ts#generateLowTurtle',
    },
  },
  {
    metadata: {
      id: 'exp-sedan-car',
      name: 'City Sedan',
      sourceType: 'generator',
      baseCategory: 'vehicle',
      subCategory: 'sedan',
      tags: ['car', 'sedan', 'vehicle', 'city', 'transport', 'automotive'],
      styleTags: ['stylized', 'compact', 'clean', 'urban'],
      shapeTags: ['wheeled', 'low_profile', 'rectangular_body', 'road_vehicle', 'four_wheeled'],
      colorTags: ['red', 'blue', 'yellow', 'white', 'black', 'gray', 'silver'],
      complexity: 'medium',
      voxelBudgetRange: { min: 140, max: 210 },
      symmetry: 'strong',
      editableParts: ['palette', 'wheels', 'roof', 'windows', 'front'],
      promptAliases: [
        'car',
        'sedan',
        'city car',
        'small car',
        'taxi',
        'compact car',
        'passenger car',
        'sedan car',
      ],
      negativeKeywords: [
        'bird',
        'rabbit',
        'castle',
        'tree',
        'penguin',
        'animal',
        'creature',
        'building',
        'house',
        'flying',
      ],
      rebuildSuitability: 'high',
      priority: 96,
      status: 'active',
      description:
        'A stylized voxel sedan car suitable for urban and city-themed scenes. ' +
        'Supports color customization, wheel sizing, and window/roof adjustments. ' +
        'Ideal for reuse in transportation-themed prompts.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/sedanCarGenerator.ts#generateSedanCar',
    },
  },
  {
    metadata: {
      id: 'exp-bus-city',
      name: 'City Bus',
      sourceType: 'generator',
      baseCategory: 'vehicle',
      subCategory: 'bus',
      tags: ['bus', 'vehicle', 'city', 'transport', 'school bus', 'shuttle', 'public transit'],
      styleTags: ['stylized', 'blocky', 'urban', 'compact'],
      shapeTags: ['wheeled', 'long_body', 'window_band', 'road_vehicle'],
      colorTags: ['yellow', 'red', 'blue', 'white', 'black'],
      complexity: 'medium',
      voxelBudgetRange: { min: 155, max: 225 },
      symmetry: 'strong',
      editableParts: ['windows', 'roof', 'front', 'wheels', 'palette'],
      promptAliases: [
        'bus',
        'city bus',
        'school bus',
        'shuttle bus',
        'public bus',
        'city shuttle',
        'urban bus',
        'transport bus',
      ],
      negativeKeywords: ['bird', 'cat', 'castle', 'tree house', 'penguin', 'dragon', 'boat', 'airplane'],
      rebuildSuitability: 'high',
      priority: 97,
      status: 'active',
      description:
        'A compact city bus template with editable window band, roof, front style, and wheels. ' +
        'Designed for urban transport prompts and school-bus style adaptations.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/busCityGenerator.ts#generateBusCity',
    },
  },
  {
    metadata: {
      id: 'exp-fire-truck',
      name: 'Fire Truck',
      sourceType: 'generator',
      baseCategory: 'vehicle',
      subCategory: 'fire_truck',
      tags: ['fire truck', 'truck', 'vehicle', 'emergency', 'rescue', 'fire engine', 'service vehicle'],
      styleTags: ['stylized', 'blocky', 'service_vehicle', 'utility'],
      shapeTags: ['wheeled', 'boxy', 'laddered', 'road_vehicle'],
      colorTags: ['red', 'white', 'black', 'gray'],
      complexity: 'medium',
      voxelBudgetRange: { min: 160, max: 230 },
      symmetry: 'strong',
      editableParts: ['ladder', 'roof', 'front', 'wheels', 'palette'],
      promptAliases: [
        'fire truck',
        'fire engine',
        'emergency truck',
        'rescue truck',
        'ladder truck',
        'city fire truck',
        'rescue engine',
        'service truck',
      ],
      negativeKeywords: ['bird', 'rabbit', 'castle', 'tree', 'boat', 'penguin', 'dragon', 'airplane'],
      rebuildSuitability: 'high',
      priority: 98,
      status: 'active',
      description:
        'A stylized fire truck template with configurable ladder, roof silhouette, and wheel profile. ' +
        'Suitable for emergency and rescue prompts with strong road-vehicle identity.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/fireTruckGenerator.ts#generateFireTruck',
    },
  },
  {
    metadata: {
      id: 'exp-house-small',
      name: 'Small House',
      sourceType: 'generator',
      baseCategory: 'building',
      subCategory: 'house',
      tags: ['house', 'home', 'building', 'cabin', 'small house', 'residence', 'cottage'],
      styleTags: ['blocky', 'cozy', 'stylized', 'neighborhood'],
      shapeTags: ['roofed', 'boxy', 'windowed', 'small_footprint', 'chimneyed'],
      colorTags: ['brown', 'beige', 'red', 'white', 'gray', 'cream'],
      complexity: 'medium',
      voxelBudgetRange: { min: 145, max: 220 },
      symmetry: 'strong',
      editableParts: ['roof', 'door', 'windows', 'chimney', 'palette'],
      promptAliases: ['house', 'small house', 'home', 'cabin', 'little house', 'cottage', 'tiny home', 'small cottage'],
      negativeKeywords: ['car', 'bus', 'bird', 'penguin', 'dragon', 'animal', 'creature', 'boat', 'airplane'],
      rebuildSuitability: 'high',
      priority: 95,
      status: 'active',
      description:
        'A compact voxel house template for neighborhood, cabin, and cottage scenes. ' +
        'Supports roof style changes, window scaling, door styling, and chimney adjustments.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/houseSmallGenerator.ts#generateSmallHouse',
    },
  },
  {
    metadata: {
      id: 'exp-boat-small',
      name: 'Small Boat',
      sourceType: 'generator',
      baseCategory: 'vehicle',
      subCategory: 'boat',
      tags: ['boat', 'ship', 'vehicle', 'watercraft', 'fishing boat', 'rescue boat', 'small boat', 'cabin boat'],
      styleTags: ['stylized', 'compact', 'scenic', 'blocky', 'nautical'],
      shapeTags: ['hull', 'long_body', 'decked', 'water_vehicle', 'bowed_front', 'cabin'],
      colorTags: ['blue', 'white', 'red', 'brown', 'yellow'],
      complexity: 'medium',
      voxelBudgetRange: { min: 140, max: 210 },
      symmetry: 'strong',
      editableParts: ['hull', 'deck', 'cabin', 'palette', 'bow', 'cabinVariant'],
      promptAliases: ['boat', 'small boat', 'ship', 'fishing boat', 'rescue boat', 'cabin boat', 'little boat', 'watercraft'],
      negativeKeywords: ['car', 'bus', 'castle', 'rabbit', 'penguin', 'animal', 'house', 'building', 'airplane', 'bird'],
      rebuildSuitability: 'high',
      priority: 93,
      status: 'active',
      description:
        'A compact voxel boat template with a readable hull, deck trim, bow, stern, and optional cabin. ' +
        'Suitable for fishing, rescue, and small watercraft prompts with palette and cabin-variant edits.',
    },
    source: {
      type: 'generator',
      ref: 'src/templates/generators/boatSmallGenerator.ts#generateSmallBoat',
    },
  },
];
